### ISSUE TITLE
Named Entity Recognition is not working in NLPCraft

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#1]
After I compared documentation from DataLingvo and NLPCraft, I couldn't find NER handling in NC, but it is present in DL. I also tested in in my app and when I am expecting metadata condition ~NLP_NE == PERSON, there is no such metadata property while token is recognized. NER is very important functionality for me. Please fix it.

**Comment by skhdl** [comment]
Will be fixed in next release  - version 0.2.0. Also alternative NLP engine (plugable) will be supported (Stanford NLP, Apache OpenNLP), which will allow you to select different implementation for NE resolution.

**Comment by Jylanthas** [comment]
@skhdl that's great news. does the release have a rough date yet ?

**Comment by vic64** [comment]
We are expecting NLPCraft 0.2.0 to be released sometime next week.

**Comment by vic64** [comment]
Resolved in 0.2.0 release.
