### ISSUE TITLE
`Probe cannot be started` error message

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#116]
The probe cannot be started without parameters.

Message is 'Exception in thread "main" org.nlpcraft.common.NCException: Either system property 'NLPCRAFT_PROBE_JARSFOLDER' or system property 'NLPCRAFT_PROBE_MODELS' must be provided.Exception in thread "main" org.nlpcraft.common.NCException: Either system property 'NLPCRAFT_PROBE_JARSFOLDER' or system property 'NLPCRAFT_PROBE_MODELS' must be provided.'

But we also we can start it with `-config=..'

So, error message should be improved.

**Comment by vic64** [comment]
Fixed in `release` branch with better log.
