### ISSUE TITLE
Trace disable property

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#117]
We need the possibility to turn the trace off to avoid warnings like
Sep 01, 2019 10:32:41 AM io.opencensus.exporter.trace.util.TimeLimitedHandler handleException
WARNING: Failed to export traces: java.util.concurrent.ExecutionException: io.jaegertracing.internal.exceptions.SenderException: Could not send 11 spans

**Comment by skhdl** [comment]
See branch GH-117 based on GH-108.
If this solution is ok, better to configure these exporters by default.

**Comment by vic64** [comment]
I'm not sure what's the problem here...

If the user configured Jaeger exporter - she needs to have Jaeger running. The system works fine without any warnings if no exporters are configured (which is the default configuration).

**Comment by skhdl** [comment]
1) ок - GH-117 deleted
2) I guess we shouldn't configure exporters by default - best variant.
The ticket can be closed.
