### ISSUE TITLE
Invalid properties names.

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#121]
Properties descrived as: NLPCRAFT_SERVER_PROBE_DOWNLINK  and NLPCRAFT_SERVER_PROBE_UPLINK 
but used as 
NLPCRAFT_SERVER_LINKS_DOWNLINK and NLPCRAFT_SERVER_LINKS_UPLINK
![изображение](https://user-images.githubusercontent.com/6073674/64714997-4fdde280-d4c8-11e9-948f-5095267a213e.png)

**Comment by vic64** [comment]
Fixed in `release` branch.
