### ISSUE TITLE
Invalid type of 'srvReqId' field in REST APIs

### ISSUE THREAD

**Issue by syermakov** [vic64/nlpcraft#127]
Please check responses of /ask and /check endpoints:

 - /ask returns 'srvReqId' as number
 - /check returns 'srvReqId' (inside 'states' field) as string

Thanks.

**Comment by vic64** [comment]
I think I fixed in `release` branch: d94d746b878e5bf220b5ebb3a78d947d739dc82c

**Comment by syermakov** [comment]
Looks good. Thanks!
