### ISSUE TITLE
Error in /cancel REST endpoint

### ISSUE THREAD

**Issue by syermakov** [vic64/nlpcraft#128]
**Describe the bug**
/cancel endpoint sometimes ends with 
`400 Bad Request: {"code":"NC_ERROR","msg":"Expected single insert count, but received 0 inserts."}" `
Looks like requests get cancelled successfully, so my guess is that this error happens during some kind of request post-processing.

**To Reproduce**
- /signin
- /ask
- Restart server
- /signin (same account)
- /cancel (specify 'srvReqIds') <-- Error

**Comment by skhdl** [comment]
ready to review GH-128

**Comment by vic64** [comment]
Merged to `release`.
