### ISSUE TITLE
Akka property `akka.http.server.remote-address-header` cannot be used in nlpcraft.conf

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#136]
val miniConfig = ConfigFactory.parseString(
     s”“”
       |akka.http.server.remote-address-header = $configValue
     “”".stripMargin)
   implicit val sys = ActorSystem(“AkkaRemoteAddressTest”, miniConfig)
we can just encode this in the code

**Comment by vic64** [comment]
Fixed and merged to `release`.

**Comment by skhdl** [comment]
ready for review in GH-113
(Akka have its own config file reference.conf)

**Comment by vic64** [comment]
So, what is fixed? I don't see any changes...

**Comment by skhdl** [comment]
Sorry, GH-137
