### ISSUE TITLE
nc:geo incorrect order of matches for subcontinent, wrong match 

### ISSUE THREAD

**Issue by ermadan** [vic64/nlpcraft#15]
Intent contains geo term:
TERM("id == nlp:geo", 0, 1)

query contains search by subcontinent: "top 5 sales in southern asia"

value of GEO_KIND by order of matches :
CITY  (GEO_CITY contains value "asia" which doesnt seem quite right)
CONTINENT
SUBCONTINENT
expected:
SUBCONTINENT
CONTINENT
CITY

probe log:
Apr-15 11:58:49 [INFO ] Sentence received: top 5 sales in southern asia
Apr-15 11:58:49 [INFO ] Sentence variant (#1 of 6) for: top 5 sales in southern asia
+==========================================================================================================================================================================================+
| nlp:index | nlp:origtext | nlp:lemma | nlp:pos | nlp:quoted | nlp:stopword | nlp:dict | nlp:wordindexes | nlp:direct | nlp:sparsity |    geo     |     num     |    aspen:salesperson    |
+==========================================================================================================================================================================================+
| 0         | top          | top       | JJ      | false      | false        | true     | [0]             | true       | 0            |            |             |                         |
| 1         | 5            | 5         | CD      | false      | false        | false    | [1]             | true       | 0            |            | =5, index=0 |                         |
| 2         | sales        | sale      | NNS     | false      | false        | true     | [2]             | true       | 0            |            |             | unid=bxl7ygnxxHgYxd27W5 |
| 3         | in           | in        | IN      | false      | false        | true     | [3]             | true       | 0            |            |             |                         |
| 4         | southern     | southern  | ---     | false      | false        | true     | [4]             | true       | 0            |            |             |                         |
| 5         | asia         | asia      | NN      | false      | false        | true     | [5]             | true       | 0            | CONTINENT  |             |                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Apr-15 11:58:49 [INFO ] Sentence variant (#2 of 6) for: top 5 sales in southern asia
+======================================================================================================================================================================================================+
| nlp:index | nlp:origtext | nlp:lemma | nlp:pos | nlp:quoted | nlp:stopword | nlp:dict | nlp:wordindexes | nlp:direct | nlp:sparsity |    geo     |        function         |    aspen:salesperson    |
+======================================================================================================================================================================================================+
| 0         | top 5        | top 5     | ---     | false      | false        | false    | [0, 1]          | true       | 0            |            | type=LIMIT, indexes=[1] |                         |
| 1         | sales        | sale      | NNS     | false      | false        | true     | [2]             | true       | 0            |            |                         | unid=bxl7ygnxxHgYxd27W5 |
| 2         | in           | in        | IN      | false      | false        | true     | [3]             | true       | 0            |            |                         |                         |
| 3         | southern     | southern  | ---     | false      | false        | true     | [4]             | true       | 0            |            |                         |                         |
| 4         | asia         | asia      | NN      | false      | false        | true     | [5]             | true       | 0            | CONTINENT  |                         |                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Apr-15 11:58:49 [INFO ] Sentence variant (#3 of 6) for: top 5 sales in southern asia
+=================================================================================================================================================================================================================================================+
| nlp:index | nlp:origtext | nlp:lemma | nlp:pos | nlp:quoted | nlp:stopword | nlp:dict | nlp:wordindexes | nlp:direct | nlp:sparsity |                          geo                          |        function         |    aspen:salesperson    |
+=================================================================================================================================================================================================================================================+
| 0         | top 5        | top 5     | ---     | false      | false        | false    | [0, 1]          | true       | 0            |                                                       | type=LIMIT, indexes=[1] |                         |
| 1         | sales        | sale      | NNS     | false      | false        | true     | [2]             | true       | 0            |                                                       |                         | unid=bxl7ygnxxHgYxd27W5 |
| 2         | in           | in        | IN      | false      | false        | true     | [3]             | true       | 0            |                                                       |                         |                         |
| 3         | southern     | southern  | ---     | false      | false        | true     | [4]             | true       | 0            |                                                       |                         |                         |
| 4         | asia         | asia      | NN      | false      | false        | true     | [5]             | true       | 0            | CITY philippines|western visayas|asia|9.5506|122.5164 |                         |                         |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Apr-15 11:58:49 [INFO ] Sentence variant (#4 of 6) for: top 5 sales in southern asia
+==============================================================================================================================================================================================================+
| nlp:index | nlp:origtext  |   nlp:lemma   | nlp:pos | nlp:quoted | nlp:stopword | nlp:dict | nlp:wordindexes | nlp:direct | nlp:sparsity |      geo      |        function         |    aspen:salesperson    |
+==============================================================================================================================================================================================================+
| 0         | top 5         | top 5         | ---     | false      | false        | false    | [0, 1]          | true       | 0            |               | type=LIMIT, indexes=[1] |                         |
| 1         | sales         | sale          | NNS     | false      | false        | true     | [2]             | true       | 0            |               |                         | unid=bxl7ygnxxHgYxd27W5 |
| 2         | in            | in            | IN      | false      | true         | true     | [3]             | true       | 0            |               |                         |                         |
| 3         | southern asia | southern asia | ---     | false      | false        | false    | [4, 5]          | true       | 0            | SUBCONTINENT  |                         |                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Apr-15 11:58:49 [INFO ] Sentence variant (#5 of 6) for: top 5 sales in southern asia
+==================================================================================================================================================================================================+
| nlp:index | nlp:origtext  |   nlp:lemma   | nlp:pos | nlp:quoted | nlp:stopword | nlp:dict | nlp:wordindexes | nlp:direct | nlp:sparsity |      geo      |     num     |    aspen:salesperson    |
+==================================================================================================================================================================================================+
| 0         | top           | top           | JJ      | false      | false        | true     | [0]             | true       | 0            |               |             |                         |
| 1         | 5             | 5             | CD      | false      | false        | false    | [1]             | true       | 0            |               | =5, index=0 |                         |
| 2         | sales         | sale          | NNS     | false      | false        | true     | [2]             | true       | 0            |               |             | unid=bxl7ygnxxHgYxd27W5 |
| 3         | in            | in            | IN      | false      | true         | true     | [3]             | true       | 0            |               |             |                         |
| 4         | southern asia | southern asia | ---     | false      | false        | false    | [4, 5]          | true       | 0            | SUBCONTINENT  |             |                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Apr-15 11:58:49 [INFO ] Sentence variant (#6 of 6) for: top 5 sales in southern asia
+=====================================================================================================================================================================================================================================+
| nlp:index | nlp:origtext | nlp:lemma | nlp:pos | nlp:quoted | nlp:stopword | nlp:dict | nlp:wordindexes | nlp:direct | nlp:sparsity |                          geo                          |     num     |    aspen:salesperson    |
+=====================================================================================================================================================================================================================================+
| 0         | top          | top       | JJ      | false      | false        | true     | [0]             | true       | 0            |                                                       |             |                         |
| 1         | 5            | 5         | CD      | false      | false        | false    | [1]             | true       | 0            |                                                       | =5, index=0 |                         |
| 2         | sales        | sale      | NNS     | false      | false        | true     | [2]             | true       | 0            |                                                       |             | unid=bxl7ygnxxHgYxd27W5 |
| 3         | in           | in        | IN      | false      | false        | true     | [3]             | true       | 0            |                                                       |             |                         |
| 4         | southern     | southern  | ---     | false      | false        | true     | [4]             | true       | 0            |                                                       |             |                         |
| 5         | asia         | asia      | NN      | false      | false        | true     | [5]             | true       | 0            | CITY philippines|western visayas|asia|9.5506|122.5164 |             |                         |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by skhdl** [comment]
ready for review NC-18
Note, the ticket is about logging ordering  - it was fixed in this branch.
I suppose that the main reason was variants ordering, so this ticket should be closed and another ticket should be created related to variants ordering issue.

**Comment by aradzinski** [comment]
In NC-18 branch? This ticket was closed months ago...

**Comment by skhdl** [comment]
GH-15
