### ISSUE TITLE
"The requested resource could not be found" while trying to add/delete datasource

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#19]
I get HTTP 404 with message "The requested resource could not be found" when I am trying to add or delete datasource. I am using NLPCraft 0.4.0 and Postman. I follow the documentation:
https://nlpcraft.docs.apiary.io/#reference/data-sources/apiv1dsadd/adds-new-data-source.

Here is my example request:

```
POST /api/v1/ds/add HTTP/1.1
Host: localhost:8081
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 4ffa372c-ea66-63dd-c048-9ad4bf6b8203

{
  "acsTok": "...",
  "name": "...",
  "shortDesc": "...",
  "mdlId": "...",
  "mdlName": "...",
  "mdlVer": "..."
}
```

The same situation is for ds/delete. Rest of requests are working well, for example /api/v1/signin. I don't know am I doing some wrong or it's error connected to newest version of NLPCraft. Please check it.

**Comment by aradzinski** [comment]
Data sources have been deleted in v0.4.0 (including their corresponding Java and REST APIs) (see [release notes](http://nlpcraft.org/release-notes-0.4.0.html)) as mostly redundant. You can simply use model ID "mdlId" field in REST '/ask' calls instead of of "dsId".

**Comment by vic64** [comment]
Can we close this?

**Comment by DankessS** [comment]
@vic64 Sorry for the delay. Thanks, all is clear, you can close this issue.
