### ISSUE TITLE
Regex token recognition works nondeterministically

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#2]
I encountered a problem with regex token recognition. It happends in both version 0.1.0 and 0.2.0.
When I use synonim with regex in my model.json file:
```
{
      "id": "x:apiToken",
      "description": "",
      "synonyms": [
        "///^\\[[a-z0-9]+\\]$///"
      ]
    }
```
and ask query "[bcac5cafe7dbe0f32a6de3026257f555f47b2398f1cd14b46ed5f5607e032e0e]"
then I expect recognition of x:apiToken in result, but it is recognized as two separated tokens and does not match x:apiToken:

![faultRecognition](https://user-images.githubusercontent.com/13571369/55620381-12e42600-579b-11e9-9f15-4f66971e2a14.PNG)

but in some cases it works well, for example for query "[5d109304e9ee9688b21141f59dad00d7ac562e3926bce5d045010b0a89ae897b]" result is:

![okRecognition](https://user-images.githubusercontent.com/13571369/55620484-49ba3c00-579b-11e9-9be8-4d44742a909e.PNG)

However, both of above queries are correct java regular expressions and match this regex:
`^\\[[a-z0-9]+\\]$`
Recognition works nondeterministically and I can't  rely on it in my app. 
Please fix it.

**Comment by DankessS** [comment]
Moreover, in DataLingvo it worked always fine.

**Comment by skhdl** [comment]
Thank you, will be checked and fixed in next release - version 0.3.0.

**Comment by aradzinski** [comment]
Does look like a simple regression.

**Comment by vic64** [comment]
Fixed in 0.3.0 release.

**Comment by DankessS** [comment]
@skhdl @aradzinski I see there is still problem with it in v 0.3.0. I use the same regex "///^\\[[a-z0-9]+\\]$///" and for this token it works fine:
![image](https://user-images.githubusercontent.com/13571369/56119808-221e5d00-5f6d-11e9-8c5d-7a4bd80fd653.png)
but this is badly recognized(as two separated tokens):
![image](https://user-images.githubusercontent.com/13571369/56120020-893c1180-5f6d-11e9-98be-26e2b3401b58.png)
more examples:
![image](https://user-images.githubusercontent.com/13571369/56120179-eb951200-5f6d-11e9-8a48-7c44dc6115a4.png)
![image](https://user-images.githubusercontent.com/13571369/56120269-167f6600-5f6e-11e9-81bd-98b09b1a9445.png)
![image](https://user-images.githubusercontent.com/13571369/56120314-2c8d2680-5f6e-11e9-9951-315bcc7cb9f7.png)

I noticed that I can get around this by changing regex to  "///^\\[[a-z0-9]+$///" and then sending value without last bracket "[eb58049a8220511e2b06754c41c4f08e520c5d90a98039f88ba7252d8abbb6a1". Then it always works.

**Comment by skhdl** [comment]
@DankessS 

1. Could you post identifiers as plain text? It is easier to copy them and test 
2. Just for confirm - are you sure that you use "stanford" NLP engine for both sides  - server and probe? (-DNLPCRAFT_NLP_ENGINE=stanford)  Different engines have different tokenization policies.
See please https://nlpcraft.org/release-notes-0.3.0.html  
I have tried one id, and seems it works fine for 0.3.0 and "stanford" NLP engine.
+=================================================================================
| nlp:index |                            nlp:origtext                            |
+=================================================================================
| 0         | test                                                               |
|           | [eb58049a8220511e2b06754c41c4f08e520c5d90a98039f88ba7252d8abbb6a1] |
+---------------------------------------------------------------------------------

**Comment by DankessS** [comment]
@skhdl Ok got it. My fault, I didn't look into release notes and not noticed info about this NLPCRAFT_NLP_ENGINE system variable. So I tested it as default on opennlp engine. Now when changed to stanford, everything works fine. Issue can be closed.
