### ISSUE TITLE
Individual tokens should have their own weight. 

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#20]
For example, a ``nlp:geo`` token should have the weight that is based on the kind of geo-location. The intent solver should use this weight for fine tuning of the matching process. Default value should be zero.

**Comment by skhdl** [comment]
ready for review in GH-35-20 (based on GH-35)
default weiпре added for each tokens type.
Only GEO ("USA" as country vs "USA" as city case)
For other cases, we can extend logic when it is necessary.

**Comment by vic64** [comment]
This code:
```java
    private def calcSystemTokensWeight(v: NCIntentSolverVariant): Int = {
        val x = v.tokens.asScala.map(t ⇒
            if (isGeo(t))
                t.getMetadata.getInteger("GEO_WEIGHT")
            else if (isNumeric(t))
                t.getMetadata.getInteger("NUM_WEIGHT")
            else if (isDate(t))
                t.getMetadata.getInteger("DATE_WEIGHT")
            else if (isCoordinate(t))
                t.getMetadata.getInteger("COORDINATE_WEIGHT")
            else if (isFunction(t))
                t.getMetadata.getInteger("FUNCTION_WEIGHT")
            else
                0
        ).sum

        x
    }
```
This looks rather bad. Why don't we keep 'weight' as a general metadata 'NLP_WEIGHT' on any token (system built-in or user-defined)?

**Comment by skhdl** [comment]
Token has only one nlp note and can have multiple other notes.
So, if we change nlp note parameters, it will have an influence on the whole token.

**Comment by skhdl** [comment]
fixed.

**Comment by aradzinski** [comment]
Accepted & merged to GH-35.
