### ISSUE TITLE
Improve conversation management with smarter context switching. NCVariant class should be removed as redundant.

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#21]
Currently, entire STM clear only by timeout. We need to have individual tokens in STM clear a) by timeout and b) after N requests that haven't used that particular token.

**Comment by aradzinski** [comment]
1. Method ``getTokens()`` on ``NCConversationContext`` should return tokens sorted from youngest to oldest.

2. Method ``getVariants()`` on ``NCSentence`` should return variants sorted from best to worst fit.

**Comment by skhdl** [comment]
ready for review. All comments are taken into account.

**Comment by aradzinski** [comment]
Reviewed, merged to master and closed.
