### ISSUE TITLE
Token property NUM_ISEQUALCONDITION is confusing when matching a single value.

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#22]
Should we not have an additional property for ``nlp:num`` tokens like NUM_SINGLE_VALUE that would indicate that token represents a single value instead of having to check three properties?

It is used in our examples and is confusing as hell...

**Comment by skhdl** [comment]
Do you mean we have to check  following 3 properies values?
meta.getDouble("NUM_TO") == meta.getDouble("NUM_FROM") && meta.getBoolean("NUM_ISEQUALCONDITION");

If yes - it is unnecessary. 
See implementation of numeric enricher
"isEqualCondition" → (from == to && fromIncl && toIncl),

I think `isEqualCondition`alredy means that is it single value.

**Comment by aradzinski** [comment]
OK. Fixed documentation in master.
