### ISSUE TITLE
org.nlpcraft.probe.mgrs.conn.NCConnectionManager should be refactored.

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#24]
System.exit should be moved from this class.

**Comment by aradzinski** [comment]
Call `System.exit()` will trigger shutdown hook which in its turn perform orderly exit (stopping managers, etc.). This call is essentially a safe way to shutdown a probe from inside. What's the problem?

**Comment by vic64** [comment]
Closing as no comments...
