### ISSUE TITLE
"London" is detected as GEO, but "london" is not.

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#25]
It doesn't work in lower case.

**Comment by vic64** [comment]
I would check how OpenNLP and Stanford CoerNLP handle this case. At the very least - this is very context dependent. E.g., "Jack London" is an author, "london square" could be a street name, "london" can be a cafeteria name...

**Comment by skhdl** [comment]
With NLP engine stanford, everything works fine.
With OpenNLP, the single word "london" is detected as POS "." for some reasons. 
So it is detected as stopword and cannot be recognized with current Geo enricher implementation.
Fix in GH-25.

**Comment by vic64** [comment]
Reviewed & merged to master. Scheduled for v0.5.0 release (next 5-10 days).
