### ISSUE TITLE
Wrong date range recognition when typing since / to and wrong timestamp value

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#30]
I am using NLPCraft v 0.4.0, stanford NLP engine and I noticed problems with recognizing date ranges.
I would like to rely on nlp:date with date ranges, but when I am asking:
"... since 9/01/2019 to 10/04/2019" it works fine and recognize token as:

`Token [id=nlp:date, text=since 9/01/2019 to 10/04/2019, group=nlp:date, value=null]`

but when I am asking "... since 9/01/2019 to 13/04/2019" (or any value in dd/04/2019 where dd > 12) and I get three separated tokens:
```
Token [id=nlp:date, text=since 9/01/2019, group=nlp:date, value=null]
Token [id=nlp:nlp, text=to, group=nlp:nlp, value=null]
Token [id=nlp:nlp, text=13/04/2019, group=nlp:nlp, value=null]
```
I have the impression that it works non-deterministically, sometimes diffrent values works and sometimes not. 

Moreover when I fetch for example metadata "DATA_FROM" from token:

`Token [id=nlp:date, text=since 9/01/2019, group=nlp:date, value=null]`

I get value 1567202400000 which is date 31.08.2019, 00:00:00.
Am I converting it wrong or it is a bug, maybe lack of support dd/MM/yyyy format?

Please verify these problems.

**Comment by aradzinski** [comment]
I think the current implementation expects dates in MDY (Month/Day/Year) format (default in US). Please try this as a short-term fix. 

It probably make sense to improve date enricher to support other formats like DMY (prevalent outside of US).

**Comment by skhdl** [comment]
ready for review GH-30
Note that different numbers' formats are not supported (dates only)

**Comment by aradzinski** [comment]
Merged to master.

**Comment by aradzinski** [comment]
REST server configuration property `server.datesFormatStyle` has been added to specify which date format should be used: `DMY`, `YMD`, `MDY`.

**Comment by DankessS** [comment]
Thank you. It can be really helpful.
