### ISSUE TITLE
Need to integrate with Goole NLP APIs for richer NER processing.

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#36]
Look at https://cloud.google.com/natural-language

**Comment by aradzinski** [comment]
@skhdl If we introduce 'stanford:geo', 'google:geo' tokens than we have to remove getMinDateTokens(), etc. methods from `NCModel` interface (as it is not symmetrical anymore).

**Comment by aradzinski** [comment]
CR comments:
1. NCDumpWriterScala is missing new model's component: enabledTokens

**Comment by skhdl** [comment]
Fixed, merged into release, GH-36 branch deleted. 
The ticket can be closed.

**Comment by aradzinski** [comment]
For the record, the following data model configuration properties have been **removed** as part of the refactoring for this ticket:
- `MAX_GEO_TOKENS`
- `MIN_GEO_TOKENS`
- `MAX_NUM_TOKENS`
- `MIN_NUM_TOKENS`
- `MAX_DATE_TOKENS`
- `MIN_DATE_TOKENS`
- `MAX_FUNCTION_TOKENS`
- `MIN_FUNCTION_TOKENS`
- `VENDOR_NAME`
- `VENDOR_URL`
- `VENDOR_CONTACT`
- `VENDOR_EMAIL`
- `DOCS_URL`
