### ISSUE TITLE
Need to add user and session metadata support.

### ISSUE THREAD

**Issue by aradzinski** [vic64/nlpcraft#41]
We need to be able to capture user session metadata like GEO location as well as general user account metadata (additionally to existing user information). Note that some enrichers can take an advantage of this information (e.g. date enricher should take user's GEO location into consideration).

**Comment by skhdl** [comment]
Ready for review GH-41 brach.
Checked under all databases.

**Comment by vic64** [comment]
Merged into `release` branch. Dev guide is TBD.
