### ISSUE TITLE
Database error after repeatedly adding the same user and attempting to log in

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#42]
I'm using NLPCraft 0.4.0 and built-in database. I noticed, it's possible to add repeatedly user with the same email address. After adding few users, when I 'm trying to signin with this user I get the database error:

`[ERROR] Unexpected error: Database error: Single value expected.
org.nlpcraft.common.NCException: Database error: Single value expected.`

It's connected with selectOne or selectSingle (I don't exactly remember) method. Please check it.

**Comment by skhdl** [comment]
Thank you. 
One question  - did you add the second user with the same email 
 - via REST API 
or directly 
 - via some JDBC calls (or console) to the built-in database?

**Comment by DankessS** [comment]
I added second and next users via REST API.

**Comment by aradzinski** [comment]
Merged to master.
