### ISSUE TITLE
Ability to catch input sentence when no matching intent can be found

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#47]
Maybe I am not aware or do not know how can I do this, but I think it could be good to be able to catch input sentence when no matching intent was found. I would like then to count edit distance of given, no recognized question and compare it with my set of defined queries. Then I could suggest user in response that maybe he meant question in diffrent syntax.

As I know, I can use 
`public NCIntentSolver(String name, Supplier<NCQueryResult> notFound)`
but there is no way to catch asked query. Any suggestions of this?

**Comment by aradzinski** [comment]
Two suggestions:
1. You can do that on REST call side where you can re-ask automatically with a different sentence or replace the received result.
2. On the model (probe) side you can use `NCSentence.getNormalizedText()` method to get the original request text. It's not currently available directly for not-found intent function but you can get `NCSentence` instance from `NCIntentSolverContext` in your intents' callbacks (and store it in a thread local, for example).

We'll fix (2) with API change in 0.6.0.

**Comment by aradzinski** [comment]
Fixed in ongoing GH-32 work. Will be released in 0.6.0. The non-found function is now accepts `NCQueryContext` as its argument.
