### ISSUE TITLE
Proposal for Spring (and probably other IoC frameworks) integration

### ISSUE THREAD

**Issue by syermakov** [vic64/nlpcraft#50]
1. Add a factory interface that will be responsible for constructing NCModelProvider instances (currently they are constructed via Class#newInstance).
For example:
```java
public interface NCModelProviderFactory {
    void initialize(Map<String, String> props);

    NCModelProvider mkProvider(String type);
}
```

2. Add an optional configuration section to probe.config that will allow users to specify which IoC framework to use. 
Something like this:
```
probe {

    ...

    modelProviderFactory {
        # IoC framwork integration class
       type = "org.nlpcraft.probe.spring.SpringModelProviderFactory"

       # Map of configuration properties for the model provider factory
       props {
             # User-defined Spring Java Config class
             javaConfig = "foo.bar.MySpringConfiguration"
             # or Spring XML file 
             xmlConfig = "./my-application.xml"
        }
    }
}
```
(if `modelProviderFactory` is not specified then we should fall back to the old Class#newInstance approach)

3. Provide an implementation of the provider factory interface that will use Spring Application Context to instantiate NCModelProvider (should support both Java Config and XML-based configurations).

**Comment by aradzinski** [comment]
An example of SpringBoot app using this?

**Comment by syermakov** [comment]
Pushed the modified Alarm example to GH-50 branch.

Please note that it is based on Spring Framework, not on Spring Boot.

For Spring Boot integration it is better to provide auto-configuration for Probe (see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html).

**Comment by aradzinski** [comment]
Few questions on GH-50:
1. Why is this in probe and not in the model API?
2. Should probably have a clear separation between an interface and two implementations (in different sub-packages like `impl/default` and `impl/spring`).

**Comment by syermakov** [comment]
Do you mean something like this?

`org.nlpcraft.model.NCModelProviderFactory`
`org.nlpcraft.model.impl.dflt.NCDefaultModelProviderFactory` - note we can't use 'default' since it is a keyword in Java
`org.nlpcraft.model.impl.spring.NCSpringModelProviderFactory`

Personally I don't like `impl` in package name since it will go to configs. 
Typically `impl` is something internal, something that shouldn't be exposed to public API. 
But that is just IMHO, not a problem to refactor:)

**Comment by aradzinski** [comment]
@syermakov 
I think we can replace:
- "impl" -> "factories"
- "deafult" -> "basic"
and it should give us a naming zen :-)

**Comment by syermakov** [comment]
Changed packages.
Ready for review.

**Comment by skhdl** [comment]
Few questions to discussion:
1. NCSpringModelProviderFactory, NCBasicModelProviderFactory - why are they implemented by java? What is the reason?
2. Strings like error messages in org.nlpcraft.model.factories.spring.NCSpringModelProviderFactory. 
Why don't we use String.format method? 
3. NCSpringModelProviderFactory  -JAVA_CONFIG_PROP and XML_CONFIG_PROP, is it possible that both of them are defined? 
4. NCSpringModelProviderFactory#mkJavaContext - why only ClassNotFoundException us cathced?

cosmetics:
NCDeployManager
 - import java.util.jar.{JarInputStream =>(!!!) JIS}  invalid symbol

 - private var providerFactory: NCModelProviderFactory = new NCBasicModelProviderFactory - type is not necessary

 -    try {            
            makeProvider
        }
       catch 
can be shorter
 -    try 
            makeProvider
       catch

**Comment by vic64** [comment]
@syermakov @skhdl 
Look at the GH-59. The `NCModelProvider` is being removed. Let's wait GH-509 is finished so that we don't so the double work.

**Comment by aradzinski** [comment]
GH-59 is in `release` branch. Not that `NCModelProvider` (and all associated armature) has been removed. I think we can proceed with this ticket now... Be careful when merging from `release` - there's going to be some merging to be done.

**Comment by vic64** [comment]
Merged to `release`.

**Comment by syermakov** [comment]
Re-created GH-50 branch.
Ready for review.

**Comment by skhdl** [comment]
I think it's done based on our last conversation
(Some code cleanup is done, maybe some comments in code from your side will be necessary, which can be added when review)

**Comment by vic64** [comment]
Merged to `release`.
