### ISSUE TITLE
Implement @NCIntent, @NCIntentRef and @NCTerm annotations.

### ISSUE THREAD

**Issue by aradzinski** [vic64/nlpcraft#56]
As a follow up for the GH-32 work. All current work in committed to `release` branch.

**Comment by vic64** [comment]
@skhdl Here's the method specification for NCIntent, NCIntentRef and NCIntentTerm annotations. The method should be:

Method should have either NCIntent or NCIntentRef annotation but not both
Method should return NCQueryResult
1st parameter should always be NCIntentSolverContext (no annotations is required)
Only one (1st) parameter is mandatory, everything else is optional.
All other optional parameters should have NCIntentTerm annotation (i.e. other parameters without this annotation are not allowed)
Annotated parameter type can be: NCToken for term (1,1) quantifier, Option[NCToken] or java.lang.Optional<NCToken> for term (0,1) quantifier, or List[NCToken] or java.util.List<NCToken> for term (_, >1) quantifier.
Both NCModel and NCModelProvider should be scanned for annotated methods.
Multiple methods in each class can be annotated. They all (from both classes) should be added to the same solver.

**Comment by skhdl** [comment]
ready for review GH-57

**Comment by vic64** [comment]
Merged to `release`.
