### ISSUE TITLE
Add spaCy (spacy.io) support for NEs and as NLP engine.

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#58]
Here's spaCy NEs:
https://spacy.io/api/annotation#named-entities

Here's an excellent overview on how to call Python from JVM:
https://stackoverflow.com/questions/8898765/calling-python-in-java

**Comment by skhdl** [comment]
GH-58 branch

**Comment by vic64** [comment]
Merged to 'release' branch. Dev guide is still TBD.
