### ISSUE TITLE
Wrong ('nlp:') fields in GEO tokens.

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#64]
Echo service shows some strange fields for example for GEO
"GEO_CITY": "paris",
 "GEO_CITYMETA": "Map(latitude -> 48.85341, population -> 2138551, timezone -> europe/paris, dem -> 42, longitude -> 2.3488)",
 "GEO_CONTIGUOUS": true,
 "GEO_CONTINENT": "europe",
 "GEO_COUNTRY": "france",
 "GEO_COUNTRYMETA": "Map(iso3 -> fra, area -> 547030.0, population -> 64768389, continent -> eu, iso -> fr, isoCode -> 250, languages -> fr-fr,frp,br,co,ca,eu,oc, capital -> paris, neighbours -> ch,de,be,lu,it,ad,mc,es, phone -> 33)",
 "GEO_KIND": "CITY",
 "GEO_LENGTH": 1,
 "GEO_MAXINDEX": 0,
 "GEO_MININDEX": 0,
 "GEO_NOTETYPE": "nlpcraft:geo",
 "GEO_REGION": "ile-de-france",
 **"GEO_SPARSITY": 0,**
 "GEO_SUBCONTINENT": "western europe",
 "GEO_UNID": "Np593GYGjuMBE4x4dKM",
 "GEO_WEIGHT": 5,
 **"GEO_WORDINDEXES": "[0]",**
 **"GEO_WORDLENGTH": 1,**
 "NLP_BRACKETED": false,
 "NLP_CHARLENGTH": 5,
 "NLP_CONTIGUOUS": true,
 "NLP_DICT": true,
 "NLP_DIRECT": true,
 "NLP_END": 5,
 "NLP_ENGLISH": true,
 "NLP_FREEWORD": false,
 "NLP_INDEX": 0,
 "NLP_LEMMA": "paris",
 "NLP_MAXINDEX": 0,
 "NLP_MININDEX": 0,
 "NLP_NORMTEXT": "paris",
 "NLP_NOTETYPE": "nlpcraft:nlp",
 "NLP_ORIGTEXT": "Paris",
 "NLP_POS": "NNP",
 "NLP_POSDESC": "Proper noun, singular",
 "NLP_QUOTED": false,
 "NLP_SPARSITY": 0,
 "NLP_START": 0,
 "NLP_STEM": "pari",
 "NLP_STOPWORD": false,
 "NLP_SWEAR": false,
 "NLP_UNID": "Np593GYRaFMBE4lVEeL",
 "NLP_WORDINDEXES": "[0]",
 "NLP_WORDLENGTH": 1

I have marked a few of them. Are they not from NLP part?

**Comment by aradzinski** [comment]
This is clearly a bug.

**Comment by skhdl** [comment]
ready for review GH-64

**Comment by aradzinski** [comment]
Merged to `release` branch.
