### ISSUE TITLE
Re-instate intent validation logic after GH-59 refactoring.

### ISSUE THREAD

**Issue by aradzinski** [vic64/nlpcraft#66]
During GH-59 refactoring all intent validation logic has been removed (as most of it cannot be done consistently). However, some basic validation needs to be added back (from previous implementation). 

I think the only following validation should be added back:
- Each TERM should have at least one RULE for token ID (warning)
- All token IDs, parent IDs, group IDs and values should be valid per the model (error)

**Comment by skhdl** [comment]
ready for discussion GH-66

**Comment by aradzinski** [comment]
Rejecting per discussion.

**Comment by aradzinski** [comment]
Made some fixes & merged to `release` branch.
