### ISSUE TITLE
org.nlpcraft.probe.mgrs.conn.NCConnectionManager#start.ctrlThread#exit logger

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#68]
org.nlpcraft.probe.mgrs.conn.NCConnectionManager#start.ctrlThread#exit should print cause for Exception. Without cause (stacktrace) it is impossible to understand error reason (main message is common and unuseful string like "Error reading data.")

**Comment by aradzinski** [comment]
Fixed in `release` branch: 991673e51e93b45efed3a4a87142caeab60f4c2d
