### ISSUE TITLE
Need to add an ability to pass extra data with the user REST '/ask' call.

### ISSUE THREAD

**Issue by aradzinski** [vic64/nlpcraft#7]
How does the current API allows to pass geo location of the user when he/she asks the question? Or any other similar *additional* information?

Something like a map-based container or an arbitrary JSON object that gets converted into map instance on Java side, and passed all the way to the model. Should be available on __NCSentence__ interface.

**Comment by skhdl** [comment]
ready for review in branch GH-10

**Comment by vic64** [comment]
Merged to master.
