### ISSUE TITLE
Make probe.conf optional for running probes.

### ISSUE THREAD

**Issue by aradzinski** [vic64/nlpcraft#72]
Right now we require `probe.conf` file for all probes. Most of the `probe.conf` config properties are default. I propose to have `NLPCRAFT_PROBE_XXX` system properties/env. variables that would override the `probe.conf` or the default values (which should be introduced). This will allow not to require `probe.conf` on example or during the development and testing. This would also simplify running data probes in container/cloud environment.

**Comment by skhdl** [comment]
Ready for review GH-72. Note that probe.conf files aren't deleted.

**Comment by aradzinski** [comment]
Merged to `release`.
