### ISSUE TITLE
NCIntentSolverContext 1st parameter should be optional for @NCIntent annotation.

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#73]
Not every callback implementation will require `NCIntentSolverContext` object. Insisting on the 1st parameter for any method annotated with `@NCIntent` to be `NCIntentSolverContext` will lead to IDE warnings of the unused method parameter.

Note also that with this change the list of parameters for the annotated method can be empty now.

**Comment by skhdl** [comment]
ready for review GH-73

**Comment by aradzinski** [comment]
Merged to `release`.
