### ISSUE TITLE
NCModelDumpWriter should not require solver as its parameter.

### ISSUE THREAD

**Issue by aradzinski** [vic64/nlpcraft#74]
Instead, this class should just take `model` and check if it implements `NCModelAdapter` which already has `getSolver()` method. Also, intent solver should obviously be optional overall for dump utility.

**Comment by skhdl** [comment]
ready for review GH-74
But why do we need it for models without solver? It is useless for us model. The goal was to debug solver intents.

**Comment by aradzinski** [comment]
Merged to `release`.
