### ISSUE TITLE
Sentence normalized text.

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#75]
It is not in lower case. Is it ok?

**Comment by aradzinski** [comment]
I think that's fine...

**Comment by skhdl** [comment]
It's confusing at least because of its name.
Normalized text of token (NLP_NORMTEXT token property)  - in lower case.
Normalized text of sentence (NORMTEXT sentence property)  - in the original case.

Maybe its OK, but at least names are confusing

**Comment by aradzinski** [comment]
Let's make lower case for both.

**Comment by skhdl** [comment]
See please GH-75 branch
We can't do it before processing because we need case information (some GEO based on case sensitive synonyms etc)

**Comment by aradzinski** [comment]
Merged to 'release'.
