### ISSUE TITLE
org.nlpcraft.probe.NCProbeConfigFile#jarsFolder property

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#76]
Now it is a mandatory field which can contain a null value. 
I guess it should be an optional field, but not nullable if exists.

**Comment by aradzinski** [comment]
Fields 'jarFolder' and 'models' are mutually exclusive.

**Comment by skhdl** [comment]
See please branch GH-76

**Comment by skhdl** [comment]
Note please that validation is in org.nlpcraft.probe.NCProbeConfig#check (line 100)

**Comment by aradzinski** [comment]
Merged to 'release'.
