### ISSUE TITLE
Wrong recognition of date tokens before 2010 year

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#77]
I get wrong recognition in NLPCraft 0.5.1 when asking question:
... since 08/25/2000
token "08/25/2000" is recognized as nlp:nlp, the same situation is for all dates before year 2010, for example 08/25/2005, 08/25/2009, but when type 08/25/2010, 08/25/2011 and so on, then token is recognized as nlp:date. I would like to notice that I have set MDY date format in application.conf and I expect date in intent solver in this way
new TERM("id == nlp:date", 0, 1)
so it is optional, but when typed in query I want it to be recognized as date.
Please check this case. If you need more info, then inform me, I will deliver it.

**Comment by skhdl** [comment]
@DankessS Could you tell me what is minimal and maximum dates values which used according to your business logic?

**Comment by DankessS** [comment]
@skhdl Minimum is year 1901 and maximum is always today. Maybe in the future will be also future dates, but maximum a few years in the future.

**Comment by skhdl** [comment]
1) Dates range re-generated (1900-2024)
2) Note that some components started in multiple thread mode now
3) Please look at NCDateConstants  - Some unused dates templates deleted. 
for example
old :"{yy|yyyy} dd {'of'|'for'|*} {MMMM|MMM}",
new "{yy|yyyy} dd {'of'|*} {MMMM|MMM}"

What do you think?

**Comment by aradzinski** [comment]
Merged to `release`.
