### ISSUE TITLE
Ability to combine intents and the model together.

### ISSUE THREAD

**Issue by vic64** [vic64/nlpcraft#81]
Right now model can be located in an external JSON/YAML file while intents can only be in the code. We need to have the ability to put intents into the same or separate file and just reference them in the code (e.g. through @NCIntentRef annotation).

**Comment by aradzinski** [comment]
Few comments:
1. Intent definition already has intent ID. In JSON/YAML file we should simply have "intents" as an array of strings. 
2. Should we add "getIntents()" to the `NCModel` to be consistent? May be not...

**Comment by skhdl** [comment]
fixed.

**Comment by aradzinski** [comment]
Rejecting per conversation. We can't have method `getIntents()` on file adapter.

**Comment by aradzinski** [comment]
Merged to `release` branch.
