### ISSUE TITLE
Error in release branch

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#84]
Jun-25 23:39:19 [ERROR] Failed to process request.
java.util.NoSuchElementException: key not found: direct
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[scala-library-2.11.12.jar:?]

**Comment by vic64** [comment]
Is this fixed? What branch?

**Comment by skhdl** [comment]
yes, it is already fixed in release
the ticket can be closed.
