### ISSUE TITLE
Cannot expect nlpcraft:nlp token despite being correctly detected by NLPCraft

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#85]
I am using NLPCraft 0.6.0.
I think it's a little confusing that there are such bult-in tokens:

```
nlpcraft:geo
nlpcraft:num
nlpcraft:function
nlpcraft:coordinate
nlpcraft:date
```

But while using NLPCraft is see there is also nlpcraft:nlp token, which is correctly recognized by system, it is also in util method ``` public static boolean isNlp(NCToken tok)```, but I can't expect it in the intent solver code, becouse I get an error:
```org.nlpcraft.common.NCException: Unknown token ID ('nlpcraft:nlp') in intent DSL rule: id == 'nlpcraft:nlp'```
Is it purposeful behavior? Or is it a bug? Please check it.

**Comment by aradzinski** [comment]
It's clearly a bug.

**Comment by skhdl** [comment]
ready for review GH-85

**Comment by vic64** [comment]
Merged to `release` branch. Scheduled for 0.7.0 release.
