### ISSUE TITLE
Ignite persistent configuration.

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#92]
We have to describe that if customers use Ignite as persistence database, they must add following property to DataStorageConfiguration bean.
<property name="walPath" value="..."/>
<property name="walArchivePath" value=".."/>
<property name="storagePath" value=".."/>

Also, we have to mention that these properties values must be absolute paths.

**Comment by vic64** [comment]
Added this to `ignite.xml`:

```xml
<property name="walPath" value="#{systemProperties['user.home']}/.nlpcraft/ignite/wal"/>
<property name="walArchivePath" value="#{systemProperties['user.home']}/.nlpcraft/ignite/wal-archive"/>
<property name="storagePath" value="#{systemProperties['user.home']}/.nlpcraft/ignite/storage"/>
```
Which would universally place Ignite storage under `.nlpcraft` folder in the current user home directory.
